### ISSUE TITLE
Needless Travis Running

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1581]
For example, if you push a commit and quickly amend a commit, travis start checking for both non-amended commit and amended commit.
I think this cause stack in travis queue and sometimes i stop needless check at travis web site.
 
my idea is add stop function for slack restart bot. 
it is not only for jsk_apc, for other jsk-ros-pkg, too.
what do you think? 
@wkentaro

**Comment by knorth55** [comment]
@wkentaro 
by the way, source code of restart bot is on github?

**Comment by wkentaro** [comment]
> it is not only for jsk_apc, for other jsk-ros-pkg, too.
what do you think?

Usually, I push the cancel button. And you can do that in jsk_apc and jsk_recognition.

> by the way, source code of restart bot is on github?

https://github.com/k-okada/tools/blob/master/travis-bot/scripts/restart.coffee#L10

**Comment by knorth55** [comment]
> Usually, I push the cancel button. And you can do that in jsk_apc and jsk_recognition.

i usually do that, too. but i thought it is easier if you can do that from slack.

**Comment by knorth55** [comment]
my point is i dont want to open that massive log page on web browser.

**Comment by wkentaro** [comment]
Yeah, it's fine.
But I'm not sure how you get to know the build number to stop.
I thought we need to go to the travis-ci page and check the build number, or use the travis command.
In the former solution we can just push the cancel button, and in the latter we can use the travis restart command.

**Comment by knorth55** [comment]
>  thought we need to go to the travis-ci page and check the build number, or use the travis command.
In the former solution we can just push the cancel button, 

you do not need to go to the page, you can check it from PR listed page on travis.
i often open only that listed page and check if travis work is duplicated.

https://travis-ci.org/start-jsk/jsk_apc/pull_requests

**Comment by wkentaro** [comment]
I see.
I usually see that page (PR listed page on travis) and open duplicated jobs in Chrome tabs.
After waiting a second, I push the cancel buttons of them.
That works for me, and I prefer this rather than talking in Slack to hubot. (Typing restar travis jsk-ros-pkg/jsk_common XXX is troublesome.)

But, if you create the cancel feature to slack bot, and add it the Chrome Extension (created by @furushchev), that would be better.
<img src="https://cloud.githubusercontent.com/assets/4310419/15631367/eac34396-25a1-11e6-9644-6d51286204b6.png" width="300px"/>

The extension works like below:
<img src="https://cloud.githubusercontent.com/assets/4310419/15631371/34fd8f34-25a2-11e6-94e9-3e2dfd3eec3d.png" width="300px" />

**Comment by knorth55** [comment]
i didn't know about this extension. adding cancel function in extension looks much better to me.
thank you
