### ISSUE TITLE
ARC2017 New Camera: Stereo + Triple Fusion with Astra mini

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#2029]
## Camera Candidates
- IR camera
    - Astra S
    - SR300
-  Stereo camera
    - use two camera
    - R200
    - multisense
-  Laser camera
    - multisense
    - rplidar
    - velodyne
   - GARMIN lidar lite

## Comparing Depth Data
|Object                  |Laser                              |Stereo                           |IR TOF                             |
|------------------------|--------------------------------|-------------------------------|---------------------------------|
|Wine Glass         |X                                      |X (Better than other)   |X                                      |
|Pencil Cup          |X                                      |X (Better than other)   |X                                      |
|Window Cleaner|△(Only label and cap)|O                                     |△(Only label and cap)|
|Water Bottle        |△(Only label and cap)|△(Only label and cap)|△(Only label and cap)|
|White Binder       |O                                     |△ (Hole in center)       |O                                     |
|Black Glove        |O                                      |△ (Hole in center)       |O                                     |
|White Towel       |O                                      |△ (Hole in center)       |O                                     |
|Light                    |O                                      |△ (Hole in center)        |O                                     |
|Others                 |O                                      |O                                     |O                                     |

Updated by @knorth55 on 2017-04-17 12:57
Updated by @knorth55 on 2017-04-18 11:10

**Comment by knorth55** [comment]
My opinion is combination of IR and stereo is good.

**Comment by knorth55** [comment]
http://rosindustrial.org/news/2016/1/13/3d-camera-survey

**Comment by knorth55** [comment]
PointGray
https://www.ptgrey.com/

**Comment by knorth55** [comment]
Idea:
Segmentation with RGB-D and get depth data wih laser sensor.
Therefore, we need RGB-D camera and laser sensor.

**Comment by k-okada** [comment]
When you choose sensor devices, you have to care about how these data will
be used.
For example if you want to segment the input image, what you need is the
features which represents the characteristics of the scene/object, and the
most important property is the reproducibility, so the accuracy of the D is
not so imporatnt and for example, if D is always NULL on the particular
object out of all APC object may good features for the segmentation.
If you want to measure the precise location, size or shape of the object,
the accuracy of the depth sensors are important and we're pretty sure that
the laser is always better than the RGBD/Stereo, so we'd better to chose
that. Current limitation of the laser is we do not have good sensors that
can take full 3D scene by one shot, that's why people is using RGBD or
Velodyne, but in our case, I do not think the this speed is not so
important at this time.
But if you want to reach to the object after measuring the location of
that, we can have another approach, move the arms until the gripper touch
the object, you can measure that information by 1D laser sensors,
approximate sensors, torque sensors of arms. This approach rely on the
reliability of these sensors, and do not have to robot-lasersensor
calibration.
Remember that we have hard "the system should work very well if the 3D
location of target is known, but the sensors is not enough accurate /
calibration is not correct / etc..." So one approach is to get accurate
sensor and find good calibration method, but another approach is to think
about how to avoid using these sensors and calibration process.


--
◉ Kei Okada


2017-04-12 14:45 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
@YutoUchimi RPLidar http://wiki.ros.org/rplidar

**Comment by knorth55** [comment]
Kinect2
![img_1567](https://cloud.githubusercontent.com/assets/9300063/25480646/94d7f4c4-2b84-11e7-9d11-da224bcf35af.JPG)

**Comment by pazeshun** [comment]
Astra Miniが2個載せられるカメラ台を、ありあわせの材料で作ってみました。
<img src="https://cloud.githubusercontent.com/assets/14994939/25747635/1eaa6376-31e3-11e7-8a8e-477385c4543f.JPG" width="480px">
ねじ固定+両面テープ固定が行えることが確認できましたが、ありあわせの材料のせいで若干強度不足です。
なお、下のようなアタッチメントを入れることで、
<img src="https://cloud.githubusercontent.com/assets/14994939/25747734/7f049624-31e3-11e7-82bc-2e64187ed970.JPG" width="480px">
Baxter標準の平行グリッパの根元にも固定できます。
<img src="(https://cloud.githubusercontent.com/assets/14994939/25747769/a2b6d17c-31e3-11e7-8015-514c059f1879.JPG" width="480px">
この設計をベースに板金を設計してみようと思っています。

**Comment by wkentaro** [comment]
FYI https://github.com/jsk-ros-pkg/jsk_recognition/pull/2104

![](https://cloud.githubusercontent.com/assets/4310419/26745216/7a5a496e-4824-11e7-9937-ed191f9de54d.png)

**Comment by YutoUchimi** [comment]
## Quad vs Triple fusion

- Quad: stereo RGB-D + laser
- Triple: stereo RGB-D

**Quad**

![quad_fusion_20170609](https://user-images.githubusercontent.com/22876283/26967851-c6f81e02-4d3a-11e7-808b-84d75620a063.png)

**Triple**

![triple_fusion_20170609](https://user-images.githubusercontent.com/22876283/26967856-cd59050e-4d3a-11e7-90b9-34ec00d1f616.png)

**Comment by YutoUchimi** [comment]
@k-okada It seems that currently we don't have much improvements by using quad sensor fusion, though we have requirements of waiting laser scans for around 10 seconds.
We should firstly use triple fusion to collect data, and maybe I can try improving use of laser next week.

**Comment by YutoUchimi** [comment]
I collected raw data and put here:

https://drive.google.com/open?id=0B1waEZT19wijb3dMZXhhcnp3Szg
